import { DetailSpot } from './detail-spot';

export  const SURF_SPOTS: DetailSpot[] = [
    {
        id: 1,
        nom: "Les Dunes",
        houle: 2.8,
        orientation: "NW-SW-S",
        hauteurSaturation: 2.5,
        type: "Beach Break",
        region: "Vendée",
        isSelected: false,
    },
    {
        id: 2,
        nom: "La Sauzaie",
        houle: 2.4,
        orientation: "W-NW-SW",
        hauteurSaturation: 3.2,
        type: "Reef",
        region: "Vendée",
        isSelected: false,
    },
    {
        id: 3,
        nom: "Sauveterre",
        houle: 3,
        orientation: "W-SW-NW",
        hauteurSaturation: 3.1,
        type: "Reef",
        region: "Vendée",
        isSelected: false,
    },
    {
        id: 4,
        nom: "Les Sables d'Olonne",
        houle: 2.5,
        orientation: "SW",
        hauteurSaturation: 2.5,
        type: "Beach Break",
        region: "Vendée",
        isSelected: false,
    },
    {
        id: 5,
        nom: "L'aubraie",
        houle: 2.8,
        orientation: "W-SW-NW",
        hauteurSaturation: 2.5,
        type: "Beach Break",
        region: "Vendée",
        isSelected: false,
    },
    {
        id: 6,
        nom: "Bud Bud",
        houle: 3.5,
        orientation: "SW-NW",
        hauteurSaturation: 2.5,
        type: "Beach Break",
        region: "Vendée",
        isSelected: false,
    }
]