import { DetailSpot } from './detail-spot';

export  const SURF_SPOTS: DetailSpot[] = [
    {
        id: 1570,
        mswId: 1570,
        nom: "Les Dunes",
        houle: 2.8,
        orientationHoule: "NW-SW-S",
        hauteurSaturation: 2.5,
        type: "Beach Break",
        region: "Vendée",
        maree: "Montante",
        vent: "15",
        directionVent: "E",
        coordonnees: "46°36'24.5\"N 1°51'16.6\"W",
        isSelected: false,
    },
    {
        id: 2,
        mswId: null,
        nom: "La Sauzaie",
        houle: 2.4,
        orientationHoule: "W-NW-SW",
        hauteurSaturation: 3.2,
        type: "Reef",
        region: "Vendée",
        maree: "Montante",
        vent: "15",
        directionVent: "E",
        coordonnees: "46°36'24.5\"N 1°51'16.6\"W",
        isSelected: false,
    },
    {
        id: 3,
        mswId: null,
        nom: "Sauveterre",
        houle: 3,
        orientationHoule: "W-SW-NW",
        hauteurSaturation: 3.1,
        type: "Reef",
        region: "Vendée",
        maree: "Montante",
        vent: "15",
        directionVent: "E",
        coordonnees: "46°36'24.5\"N 1°51'16.6\"W",
        isSelected: false,
    },
    {
        id: 4,
        mswId: null,
        nom: "Les Sables d'Olonne",
        houle: 2.5,
        orientationHoule: "SW",
        hauteurSaturation: 2.5,
        type: "Beach Break",
        region: "Vendée",
        maree: "Montante",
        vent: "15",
        directionVent: "E",
        coordonnees: "46°36'24.5\"N 1°51'16.6\"W",
        isSelected: false,
    },
    {
        id: 5,
        mswId: null,
        nom: "L'aubraie",
        houle: 2.8,
        orientationHoule: "W-SW-NW",
        hauteurSaturation: 2.5,
        type: "Beach Break",
        region: "Vendée",
        maree: "Montante",
        vent: "15",
        directionVent: "E",
        coordonnees: "46°36'24.5\"N 1°51'16.6\"W",
        isSelected: false,
    },
    {
        id: 6,
        mswId: 1573,
        nom: "Bud Bud",
        houle: 3.5,
        orientationHoule: "SW-NW",
        hauteurSaturation: 2.5,
        type: "Beach Break",
        region: "Vendée",
        maree: "Montante",
        vent: "15",
        directionVent: "E",
        coordonnees: "46°36'24.5\"N 1°51'16.6\"W",
        isSelected: false,
    }
]